vim.keymap.set("n", "<leader>v", ":Telescope neoclip<CR>", { desc = "[C]lipboard history" })
vim.keymap.set("n", "K", vim.lsp.buf.hover, { desc = "Show [L]SP hover info" })
vim.keymap.set("n", "<leader>gd", vim.lsp.buf.definition, { desc = "[G]oto [D]efinition" })
vim.keymap.set("n", "<leader>gr", vim.lsp.buf.references, { desc = "[G]oto [R]eferences" })
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, { desc = "[C]ode [A]ctions" })
vim.keymap.set('n','<C-n>',':Neotree filesystem reveal left<CR>', { desc = "[N]eotree [F]ilesystem" })
vim.keymap.set("n", "<leader>gf", vim.lsp.buf.format, { desc = "[G]format code" })
